Metadata:
  AWS::CloudFormation::Interface:
    ParameterGroups:
      -
        Label:
          default: "App Environment Configuration"
        Parameters:
          - ENVIRONMENT
          - MinSize
          - MaxSize
          - DesiredCapacity
Parameters:

  SecurityGroup:
        Description: Select the Security Group to use for the Launch Configuration
        Type: AWS::EC2::SecurityGroup::Id

  DatabaseName:
    Type: String
    Default: wordpress
    MinLength: 1
    MaxLength: 64
    AllowedPattern: "[a-zA-Z][a-zA-Z0-9]*" # start with a letter, only alphanumeric characters - new for this lesson
  DatabaseUser:
    Type: String
    MinLength: 1
    MaxLength: 16
    Default: wordpress
    AllowedPattern: "[a-zA-Z][a-zA-Z0-9]*" # start with a letter, only alphanumeric characters - new for this lesson
  DatabasePassword:
    Type: String
    MinLength: 8
    MaxLength: 41
    Default: w0rdpr355
    NoEcho: true
    AllowedPattern: "[a-zA-Z0-9]*" # Must only contain alphanumeric characters - new for this lesson
  ENVIRONMENT:
    Type: String
    Description: Type of environment to provision
    Default: DEV
    AllowedValues:
      - DEV
      - TEST
      - PROD
      - PRESALES
  MinSize:
    Type: String
    Description: Minimum number of app servers
    Default: "1"
  MaxSize:
    Type: String
    Description: Maximum number of app servers (Desired x 2)
    Default: "2"
  DesiredCapacity:
    Type: String
    Description: Nominal Size of APP Env
    Default: "1"

Mappings:
  RegionMap:
    us-east-1:
      "AMALINUX" : "ami-c481fad3" # AMALINUX SEP 2016
    us-east-2:
      "AMALINUX" : "ami-71ca9114" # AMALINUX SEP 2016
    us-west-1:
      "AMALINUX" : "ami-de347abe" # AMALINUX SEP 2016
    us-west-2:
      "AMALINUX" : "ami-b04e92d0" # AMALINUX SEP 2016
    ca-central-1:
      "AMALINUX" : "ami-eb20928f" # AMALINUX SEP 2016 v01
    eu-west-1:
      "AMALINUX" : "ami-d41d58a7" # AMALINUX SEP 2016
    eu-central-1:
      "AMALINUX" : "ami-0044b96f" # AMALINUX SEP 2016
    eu-west-2:
      "AMALINUX" : "ami-bfe0eadb" # AMALINUX SEP 2016 v01
    ap-southeast-1:
      "AMALINUX" : "ami-7243e611" # AMALINUX SEP 2016
    ap-southeast-2:
      "AMALINUX" : "ami-55d4e436" # AMALINUX SEP 2016
    ap-northeast-2:
      "AMALINUX" : "ami-a04297ce" # AMALINUX SEP 2016
    ap-northeast-1:
      "AMALINUX" : "ami-1a15c77b" # AMALINUX SEP 2016
    ap-south-1:
      "AMALINUX" : "ami-cacbbea5" # AMALINUX SEP 2016
    sa-east-1:
      "AMALINUX" : "ami-b777e4db" # AMALINUX SEP 2016
  InstanceSize:
    DEV:
      "EC2" : "t2.micro"
      "DB" : "db.t2.micro"
    TEST:
      "EC2" : "t2.micro"
      "DB" : "db.t2.small"
    PROD:
      "EC2" : "t2.small"
      "DB" : "db.t2.medium"
    PRESALES:
      "EC2" : "t2.micro"
      "DB" : "db.t2.medium"
Resources:
#  DB:
#    Type: "AWS::RDS::DBInstance"
#    Properties:
#      AllocatedStorage: 5
#      StorageType: gp2
#      DBInstanceClass: !FindInMap [InstanceSize, !Ref ENVIRONMENT, DB] # Dynamic mapping + Pseudo Parameter
#      DBName: !Ref DatabaseName
#      Engine: postgres
#      MasterUsername: !Ref DatabaseUser
#      MasterUserPassword: !Ref DatabasePassword
  AutoScalingGroup:
    Type: "AWS::AutoScaling::AutoScalingGroup"
    Properties:
      Cooldown: "300"
      DesiredCapacity: !Ref DesiredCapacity
      HealthCheckGracePeriod: "300"
      HealthCheckType: ELB
      LaunchConfigurationName: !Ref LaunchConfiguration
      LoadBalancerNames:
        - !ImportValue elbandsubnets-elb
      MaxSize: !Ref MaxSize
      MinSize: !Ref MinSize
      VPCZoneIdentifier:
        - !ImportValue elbandsubnets-subnetprivatea
        - !ImportValue elbandsubnets-subnetprivateb
#  EC2Instance:
#    Type: "AWS::EC2::Instance"
#    Properties:
##      InstanceType: t2.micro
  #    KeyName: AdvancedCFN
  #    NetworkInterfaces:
  #      - AssociatePublicIpAddress: "true"
  ##        GroupSet: !ImportValue securitygroups-sg1
    #      SubnetId: !ImportValue elbandsubnets-subnetpublica

  LaunchConfiguration:
    Type: "AWS::AutoScaling::LaunchConfiguration"
    Properties:
      ImageId: !FindInMap [RegionMap, !Ref "AWS::Region", AMALINUX]
      InstanceType: !FindInMap [InstanceSize, !Ref ENVIRONMENT, EC2]
      KeyName: AdvancedCFN
      SecurityGroups:
        - !Ref SecurityGroup
      UserData:
        "Fn::Base64":
          !Sub |
            #!/bin/bash
            yum update -y
            yum install httpd -y
            service httpd start
            chkconfig httpd on
            echo "Welcome to My Domain" > /var/www/html/index.html
